version: "3.9"
services:
  frontend:
    build: ./frontend
    
     
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend/venv
     
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
    depends_on:
      - db

  db:
    build: ./db
    ports:
      - "3300:3306"
    
# volumes:
#   db-data: {}






# version: "3.9"
# services:
  # database:
  #   build: ./db
  #   ports:
  #     - "3300:3306"



  # backend:
  #   container_name: server
  #   build: ./server/
  #   ports:
  #     - "8000:8000"
    
  #   env_file:
  #     - .env
    
  #   volumes:
  #     - ./server/app/:/app/
  #     - ./certs:/certs
    
  #   networks:
  #     - mysql_network
  #     - es
  #   depends_on:
  #     - databse
    
  #   restart: always